### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by ghost** [ptitSeb/RtCW-OpenPandora#2]
Hi ptit, I am a bit confuse, I cant find any pandora definition, where are the solutions?
another thing, this is the only working arm repo for this game??
I want to compile it on rpi4, obviously. thanks on advance.

**Comment by ptitSeb** [comment]
As written in the readme, you need `cons` to build, it's a Construct project (the original was like that, and I didn't migrate it to cmake or something like that). `cons` is already there, so it should work. If it doesn't, install `perl` if needed.

There isn't much define for this one, but you should be able to hack it to build it by changing value inside the `Construct` script inside `src/unix`, at least you'll find build flags there.

**Comment by ghost** [comment]
I found armhf binaries! so, closing this! thankss!!! it runs amazing on rpi4
